apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-deployment
  namespace: orderly
spec:
  selector:
    matchLabels:
      app: broker
  replicas: 1
  template:
    metadata:
      labels:
        app: broker
    spec:
      containers:
      - name: broker-container
        image: rabbitmq:3.12-management
        resources:
          requests:
            memory: '256Mi'
            cpu: '100m'
          limits:
            memory: "512Mi"
            cpu: "200m"
        envFrom:
        - configMapRef:
            name: broker-configmap
        ports:
        - containerPort: 5672
        - containerPort: 15672
        startupProbe:
          tcpSocket:
            port: 5672
          periodSeconds: 5
          failureThreshold: 30
        readinessProbe:
          tcpSocket:
            port: 5672
          periodSeconds: 3
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 5672
          periodSeconds: 1
          failureThreshold: 3
