apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: orderly
spec:
  replicas: 1 # Você pode ajustar o número de réplicas conforme necessário
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      automountServiceAccountToken: false
      containers:
      - name: nginx-container
        image: nginx:latest # Use a imagem do NGINX que você já está usando no Docker
        ports:
        - containerPort: 80 # Porta que o NGINX está ouvindo
        resources:
          requests: # requisita recursos
            memory: '500Mi'
            cpu: '1'
          limits: # limita a utilização dos recursos
            memory: "500Mi"
            cpu: "1"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
