apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: orderly
data:
  kong-config.yml: |
    _format_version: "1.1"

    services:
    - name: categories
      url: http://api-service:3000/products/category
      routes:
      - name: get-categories
        methods: [GET]
        paths:
        - /categories
        plugins:
        - name: rate-limiting
          config:
            second: 3
            minute: 5
            hour: 10
            policy: local
        strip_path: true

    - name: api
      url: http://api-service:3000
      routes:
      - name: customers
        methods: [GET, POST]
        paths:
        - /customers
        - /customers/(?<cpf>\d+)
        plugins:
        - name: request-transformer
          config:
            add:
              headers:
              - "Content-Type: application/json"
        strip_path: false
      - name: orders
        methods: [GET, POST]
        paths:
        - /orders
        - /orders/(?<id>\d+)/prepare
        - /orders/(?<id>\d+)/withdrawn
        - /orders/customer/(?<id>\d+)
        - /orders/(?<id>\d+)/status
        plugins:
        - name: request-transformer
          config:
            add:
              headers:
              - "Content-Type: application/json"
        strip_path: false
      - name: products
        paths:
        - /products
        - /products/(?<id>\d+)
        - /products/category/(?<id>\d+)
        plugins:
        - name: request-transformer
          config:
            add:
              headers:
              - "Content-Type: application/json"
        methods: [POST, PUT, DELETE, GET]
        strip_path: false

      - name: payments
        methods: [GET, POST, DELETE]
        paths:
        - /payments/order/(?<id>\d+)
        - /payments/order/(?<id>\d+)/approve
        - /payments/order/(?<id>\d+)/cancel
        plugins:
        - name: http-log
          config:
            http_endpoint: https://webhook.site/2372f3a5-5ffc-4291-8e6a-ace1b16621e4
            method: POST
        - name: request-transformer
          config:
            add:
              headers:
              - "Content-Type: application/json"
        strip_path: false
